/*
  # Profile Vitrine — Extended Columns

  ## Purpose
  Extend capability_profiles to support premium AI-generated storefront ("vitrine") features.
  Each profile can now carry:
    - AI-generated marketing copy (hero title, bio, pitch)
    - Services/products with pricing and descriptions
    - Portfolio/realizations items
    - FAQ items generated by AI
    - Trust signals (response time, volume, badges)
    - Vitrine configuration flags

  ## New Columns

  ### AI-generated copy
  - `vitrine_hero_title`   — punchy AI-generated headline (e.g. "Votre expert comptable local, disponible sous 24h")
  - `vitrine_bio`         — AI-written seller bio (warm, credible, human tone)
  - `vitrine_pitch`       — 1-sentence commercial promise shown under name
  - `vitrine_generated_at`— timestamp of last AI generation pass

  ### Services/offers (stored as JSONB array)
  - `vitrine_services`    — [{title, description, price_hint, format, highlight}]

  ### Portfolio (JSONB array)
  - `vitrine_portfolio`   — [{title, description, image_url, tags}]

  ### FAQ (JSONB array)
  - `vitrine_faq`         — [{question, answer}]

  ### Trust signals
  - `vitrine_response_time` — e.g. "Répond en moins de 2h"
  - `vitrine_badges`        — text[] e.g. ["Vérifié", "Top contributeur", "Réponse rapide"]

  ### Profile type hint for layout variant
  (profile_type already exists — artisan / independant / formateur / association / entreprise / individual)

  ## Security
  - Users can update their own vitrine columns (existing RLS SELECT/UPDATE policies cover this)
  - No new RLS needed: capability_profiles RLS is already in place
*/

DO $$
BEGIN
  -- AI-generated copy
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_hero_title') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_hero_title text DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_bio') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_bio text DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_pitch') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_pitch text DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_generated_at') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_generated_at timestamptz DEFAULT NULL;
  END IF;

  -- Services / offers
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_services') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_services jsonb DEFAULT '[]'::jsonb;
  END IF;

  -- Portfolio
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_portfolio') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_portfolio jsonb DEFAULT '[]'::jsonb;
  END IF;

  -- FAQ
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_faq') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_faq jsonb DEFAULT '[]'::jsonb;
  END IF;

  -- Trust signals
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_response_time') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_response_time text DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='capability_profiles' AND column_name='vitrine_badges') THEN
    ALTER TABLE capability_profiles ADD COLUMN vitrine_badges text[] DEFAULT ARRAY[]::text[];
  END IF;
END $$;
